services:
  calibre-web-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calibre-web-server
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      # Core runtime settings (override as needed)
      CALIBRE_WEB_PLUGINS: users_books
      CALIBRE_WEB_HOST: 0.0.0.0
      CALIBRE_WEB_PORT: 8083
      CALIBRE_DBPATH: /app/config
      # Set to "1" or "true" for development only
      CALIBRE_WEB_DEBUG: "1"

      TZ: Europe/Riga

      # Optional: if you later run as a specific UID/GID inside the container build args
      # APP_UID: "1000"
      # APP_GID: "1000"

    # Bind mounts for live development. For production you may prefer only data/config.
    volumes:
      - ./config:/app/config
      - ./var/data:/app/data
      - ./plugins:/app/plugins
      - ./entrypoint:/app/entrypoint
      # Uncomment if you want to inspect/override upstream code locally (read-only recommended)
      # - ./calibre-web:/app/calibre-web:ro

    # If you introduce external services later (e.g., a database), add depends_on.
    # depends_on:
    #   - some_db

    # Leverage the HEALTHCHECK defined in the Dockerfile (no extra definition needed here)
    # If you wanted to override:
    # healthcheck:
    #   test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://127.0.0.1:8083/plugin/users_books/health\")' || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 20s
# Named volumes alternative (commented). Use if you prefer Docker-managed storage:
# volumes:
#   calibre_config:
#   calibre_data:

# To switch to named volumes replace in the service:
#   - calibre_config:/app/config
#   - calibre_data:/app/data
